name: Website

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: midgerate
          GIT_PASS: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          pnpm run --filter website deploy