name: Website

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install deps and build (with cache)
        working-directory: website
        uses: bahmutov/npm-install@v1
      
      - name: Build website
        working-directory: website
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build